# this is a toml

title = "toml exaples"
# redis = "127.0.0.1:6379"  # redis

[mysql]
host = "192.168.1.1"
port = 3306
username = "root"
password = "mysql123456"

[redis]
host = "192.168.1.2"
port = 6379
password = "redis123456"
database = 0