redis:
  admin:
    addr: "172.0.63.79:6379"
    password: "Redis#123"
    db: 0
mysql:
  driver: "mysql"
  uri:
    "root:Mysql#123@tcp(localhost:3306)/user?charset=utf8&parseTime=True&loc=Local&multiStatements=true"
jwt:
  secret: "ayunw@#3321#@Sky"